[project]
name = "mayaflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "appdirs>=1.4.4",
    "pyside2>=5.15.2.1",
    "pyyaml>=6.0.1",
]
