# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(432, 541)
        mainWindow.setStyleSheet("QWidget#mainWindow{\n"
                                 "    background-color:#1D1F21;\n"
                                 "}\n"
                                 "\n"
                                 "QWidget#mainWindow >QFrame{\n"
                                 "    background-color:#444648;\n"
                                 "    border-radius:10px;\n"
                                 "}\n"
                                 "QTreeWidget{\n"
                                 "    background-color:#2c2e30;\n"
                                 "    border:None;\n"
                                 "    \n"
                                 "}\n"
                                 "QHeaderView::section{\n"
                                 "    background-color:#2c2e30;\n"
                                 "    color:#FFFFFF;\n"
                                 "    border-bottom:1px solid #1D1F21;\n"
                                 "\n"
                                 "}\n"
                                 "\n"
                                 "QLabel,QCheckBox,QGroupBox{\n"
                                 "    color:#FFFFFF;\n"
                                 "    font-family:\"Arial Black\";\n"
                                 "    font-size:11px;\n"
                                 "}\n"
                                 "QRadioButton{\n"
                                 "    color:#FFFFFF;\n"
                                 "    font-family:\"Arial\";\n"
                                 "    font-size:11px;\n"
                                 "}")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(mainWindow)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_left = QtWidgets.QFrame(mainWindow)
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_left)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.treeWidget_outline = QtWidgets.QTreeWidget(self.frame_left)
        self.treeWidget_outline.setColumnCount(2)
        self.treeWidget_outline.setObjectName("treeWidget_outline")
        self.treeWidget_outline.headerItem().setText(0, "1")
        self.treeWidget_outline.headerItem().setText(1, "2")
        self.treeWidget_outline.header().setVisible(True)
        self.verticalLayout.addWidget(self.treeWidget_outline)
        self.verticalLayout_5.addWidget(self.frame_left)
        self.frame_right = QtWidgets.QFrame(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_right.sizePolicy().hasHeightForWidth())
        self.frame_right.setSizePolicy(sizePolicy)
        self.frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_arnold = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_arnold.setObjectName("radioButton_arnold")
        self.horizontalLayout.addWidget(self.radioButton_arnold)
        self.radioButton_redshift = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_redshift.setObjectName("radioButton_redshift")
        self.horizontalLayout.addWidget(self.radioButton_redshift)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_path = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_path)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_start_frame = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_start_frame.setObjectName("lineEdit_start_frame")
        self.horizontalLayout_3.addWidget(self.lineEdit_start_frame)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_end_frame = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_end_frame.setObjectName("lineEdit_end_frame")
        self.horizontalLayout_3.addWidget(self.lineEdit_end_frame)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_auto_config = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_auto_config.setObjectName("pushButton_auto_config")
        self.verticalLayout_3.addWidget(self.pushButton_auto_config)
        self.pushButton_export = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_export.setObjectName("pushButton_export")
        self.verticalLayout_3.addWidget(self.pushButton_export)
        self.pushButton_add = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout_3.addWidget(self.pushButton_add)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_5.addWidget(self.frame_right)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "AlembicTool"))
        self.label.setText(_translate("mainWindow", "Outline:"))
        self.label_6.setText(_translate("mainWindow", "Render:"))
        self.radioButton_arnold.setText(_translate("mainWindow", "Arnold"))
        self.radioButton_redshift.setText(_translate("mainWindow", "RedShift"))
        self.label_2.setText(_translate("mainWindow", "Path："))
        self.label_4.setText(_translate("mainWindow", "Frame:"))
        self.label_5.setText(_translate("mainWindow", "to"))
        self.groupBox.setTitle(_translate("mainWindow", "Export"))
        self.pushButton_auto_config.setText(_translate("mainWindow", "Auto Config"))
        self.pushButton_export.setText(_translate("mainWindow", "Export"))
        self.pushButton_add.setText(_translate("mainWindow", "Add"))
