
proj_xn_tbp:
  asset:
    Char:
      Surfacing:
        - file_name: more_than_face
          show_name: 超过4边的面
          order: 0
          show: true
          allow_skip: false
          allow_fix: true
          description: 检查超过4边的面
        - file_name: 
    Prop:
      parent: "{proj_temp_test}{asset}{Char}"
    Set:
      parent: "{proj_temp_test}{asset}{Char}"