proj_temp_test:
  abc:
    Surfacing:
      - name: check_task
        show_name: 确认任务信息
        order: 0
      - name: publish_file
        show_name: 提交Maya工程
        order: 1
      - name: note
        show_name: 填写note信息
        order: 2

proj_xn_tbp:
  abc:
    Surfacing:
      - name: check_task
        show_name: 确认任务信息
        order: 0
      - name: publish_file
        show_name: 提交Maya工程
        order: 1
      - name: note
        show_name: 填写note信息
        order: 2