# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 429)
        Form.setStyleSheet("QLabel#label_head_img{\n"
                           "    width:20%;\n"
                           "    margin-left: 10px;\n"
                           "    border-radius: 25px;\n"
                           "    background: white\n"
                           "}\n"
                           "QLabel#label_name{\n"
                           "    font-family: \"Arial Black\";\n"
                           "    letter-spacing: 3px;\n"
                           "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_project = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_project.setObjectName("comboBox_project")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_project)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_asset = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_asset.setChecked(True)
        self.radioButton_asset.setObjectName("radioButton_asset")
        self.horizontalLayout_2.addWidget(self.radioButton_asset)
        self.radioButton_shot = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_shot.setObjectName("radioButton_shot")
        self.horizontalLayout_2.addWidget(self.radioButton_shot)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_asset = QtWidgets.QWidget()
        self.page_asset.setObjectName("page_asset")
        self.formLayout_2 = QtWidgets.QFormLayout(self.page_asset)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setSpacing(12)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.page_asset)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_asset_pipeline = QtWidgets.QComboBox(self.page_asset)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_asset_pipeline.sizePolicy().hasHeightForWidth())
        self.comboBox_asset_pipeline.setSizePolicy(sizePolicy)
        self.comboBox_asset_pipeline.setObjectName("comboBox_asset_pipeline")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_asset_pipeline)
        self.label_4 = QtWidgets.QLabel(self.page_asset)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.listWidget_asset_task = QtWidgets.QListWidget(self.page_asset)
        self.listWidget_asset_task.setObjectName("listWidget_asset_task")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.listWidget_asset_task)
        self.stackedWidget.addWidget(self.page_asset)
        self.page_shot = QtWidgets.QWidget()
        self.page_shot.setObjectName("page_shot")
        self.formLayout_3 = QtWidgets.QFormLayout(self.page_shot)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setSpacing(12)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.page_shot)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_shot_pipeline = QtWidgets.QComboBox(self.page_shot)
        self.comboBox_shot_pipeline.setObjectName("comboBox_shot_pipeline")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_shot_pipeline)
        self.label_6 = QtWidgets.QLabel(self.page_shot)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.treeWidget_shot_task = QtWidgets.QTreeWidget(self.page_shot)
        self.treeWidget_shot_task.setObjectName("treeWidget_shot_task")
        self.treeWidget_shot_task.headerItem().setText(0, "1")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.treeWidget_shot_task)
        self.stackedWidget.addWidget(self.page_shot)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.pushButton_submit = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.verticalLayout_3.addWidget(self.pushButton_submit)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "任务选择"))
        self.label.setText(_translate("Form", "项目:"))
        self.label_2.setText(_translate("Form", "模块:"))
        self.radioButton_asset.setText(_translate("Form", "Asset"))
        self.radioButton_shot.setText(_translate("Form", "Shot"))
        self.label_3.setText(_translate("Form", "阶段："))
        self.label_4.setText(_translate("Form", "任务:"))
        self.label_5.setText(_translate("Form", "阶段"))
        self.label_6.setText(_translate("Form", "镜头"))
        self.pushButton_submit.setText(_translate("Form", "确定"))
