proj_csx2:
  usd:
    Mod:
      - name: check_artist
        show_name: 检查制作者是否匹配
        order: 0
      - name: change_smooth_subdivide
        show_name: 修正细分模型(3 -> 1)
        order: 1
      - name: fix_group
        show_name: 修正组名（没有已GRP为结尾）
        order: 2
      - name: publish_file
        show_name: 提交Maya工程
        order: 3
      - name: export_mesh_usd
        show_name: 导出Mod_Usd
        order: 4
      - name: note
        show_name: 填写note信息
        order: 5
      - name: change_status
        show_name: 修改CGT任务状态
        order: 6
    Shader:
      - name: check_artist
        show_name: 检查制作者是否匹配
        order: 0
      - name: change_smooth_subdivide
        show_name: 修正细分模型(3 -> 1)
        order: 1
      - name: fix_group
        show_name: 修正组名（没有已GRP为结尾）
        order: 2
      - name: change_aiImage_to_tx
        show_name: 修改aiImage到tx
        order: 3
      - name: export_mesh_usd
        show_name: 导出Mod_Usd
        order: 4
      - name: export_shader_usd
        show_name: 导出Shader_Usd
        order: 5
      - name: export_asset_usd
        show_name: 导出Asset_Usd
        order: 6
      - name: publish_file
        show_name: 提交Maya工程
        order: 7
      - name: note
        show_name: 填写note信息
        order: 8
      - name: change_status
        show_name: 修改CGT任务状态
        order: 9
    Rig:
      - name: check_artist
        show_name: 检查制作者是否匹配
        order: 0
      - name: publish_file
        show_name: 提交Maya工程
        order: 1
      - name: note
        show_name: 填写note信息
        order: 2
      - name: change_status
        show_name: 修改CGT任务状态
        order: 3
    Track:
      - name: check_artist
        show_name: 检查制作者是否匹配
        order: 0
      - name: publish_file
        show_name: 提交Maya工程
        order: 1
    Model:
      - name: check_artist
        show_name: 检查制作者是否匹配
        order: 0
      - name: publish_file
        show_name: 提交Maya工程
        order: 1
      - name: generate_abc
        show_name: 生成ABC文件
        order: 2
      - name: note
        show_name: 填写note信息
        order: 3
      - name: change_status
        show_name: 修改CGT任务状态
        order: 4

proj_xsj:
  usd:
    Mod:
      parent: "{proj_csx2}"

proj_temp_test:
  abc:
    Surfacing:
      - name: publish_file
        show_name: 提交Maya工程
        order: 0
      - name: note
        show_name: 填写note信息
        order: 1
      - name: change_status
        show_name: 修改CGT任务状态
        order: 2